### ISSUE TITLE
Version 0.2.1 not resolving from maven central

### ISSUE THREAD

**Issue by cwensel** [hosuaby/inject-resources#10]
For what ever reason

```
 testImplementation 'io.hosuaby:inject-resources-junit-jupiter:0.2.1'
 testImplementation 'io.hosuaby:inject-resources-core:0.2.1'
```

does not resolve locally for me, but changing to version 0.2.0 does (yet has a bug resolved in 0.2.1).

It's clearly in Maven https://repo1.maven.org/maven2/io/hosuaby/inject-resources-junit-jupiter/0.2.1/

This may resolve itself in time and/or simply a local issue to me, but I thought I'd give you a heads up in case it's an issue with the pom generation at build time.

fyi `Gradle 6.8.3`

also, moving to maven central after bintray abandoning open source projects is a pita.

**Comment by hosuaby** [comment]
Hello, @cwensel 
I cleared the local gradle cache and downloaded `0.2.1` again.

Did you not forgot to add `mavenCentral` as you gradle repository:

```groovy
repositories {
    mavenCentral()
}
```
