### ISSUE TITLE
No guide on resource file path

### ISSUE THREAD

**Issue by bnayagrawal** [hosuaby/inject-resources#19]
Why there's no documentation of where the resource file should be? Whether it has to be a relative path, an absolute path, or whether the file should be inside the same folder of the class being tested? I am getting only null pointer exceptions. it says resource not found!

```
// Test Class Location ​
projectname/src/test/java/xyz/company/app/helpers/TestClass.java

// Resource file location
projectname/src/test/java/xyz/company/app/helpers/dummy_form_data.json

// Inside the TestClass

// Neither this works
@GivenJsonResource("dummy_form_data.json")

// Nor this works
@GivenJsonResource("/xyz/company/app/helpers/dummy_form_data.json")
```

What am I doing wrong exactly?

**Comment by hosuaby** [comment]
Hello @bnayagrawal 

All resources must be stored in ether:
projectname/src/test/resources/
or
projectname/src/main/resources/

So, `@GivenJsonResource("dummy_form_data.json")` will be resolved to `projectname/src/test/resources/dummy_form_data.json`.

**Comment by bnayagrawal** [comment]
That works. Thank you for your quick response! You should include that in the documentation I think as I could not find those details there!
