### ISSUE TITLE
Support for Spring 6

### ISSUE THREAD

**Issue by crizzis** [hosuaby/inject-resources#21]
The Spring module does not work with Spring 6, because the (previously deprecated) `InstantiationAwareBeanPostProcessorAdapter` has been removed. 

Might be able to create a PR with a backwards-compatible fix for this problem later today.

**Comment by crizzis** [comment]
Thanks! When can we expect a Maven release with this change?

**Comment by hosuaby** [comment]
@crizzis this fix is now available in release `0.3.3`.
