### ISSUE TITLE
Deploy on maven central

### ISSUE THREAD

**Issue by gbaso** [hosuaby/inject-resources#6]
[Bintray is now deprecated](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), please consider migrating to maven center

**Comment by hosuaby** [comment]
Hello, @gbaso. Yes, I was planning to do it.

**Comment by hosuaby** [comment]
Done. Since version `0.2.0` project artifacts are deployed on Macen Central. Enjoy :)
